name: example
description: "Example for Flutter Hooks + Async Redux"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2 # or newer
  async_redux: ^24.2.2 # or newer
  flutter_hooks_async_redux:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
